export const menuCatalog = [
  {
    label: "Цветные металлы",
    href: "tsvetnoi-prokat",
    metaData: "Купить Цветной металлопрокат оптом и в розницу",
    links: [
      {
        title: "Алюминий",
        link: "tsvetnoi-prokat/aluminum",
        img: "aluminumImg",
        metaData: "Алюминиевый Прокат купить",
      },
      {
        title: "Бронза",
        link: "tsvetnoi-prokat/bronze",
        img: "bronzeImg",
        metaData: "Бронзовый Прокат купить",
      },
      {
        title: "Дюраль",
        link: "tsvetnoi-prokat/dural",
        img: "duralImg",
        metaData: "Дюралевый Прокат купить",
      },
      {
        title: "Олово",
        link: "tsvetnoi-prokat/olovo",
        img: "olovoImg",
        metaData: "Оловянный Прокат купить",
      },
      {
        title: "Титан",
        link: "tsvetnoi-prokat/titan",
        img: "titanImg",
        metaData: "Титановый Прокат купить",
      },
      {
        title: "Медь",
        link: "tsvetnoi-prokat/copper",
        img: "copperImg",
        metaData: "Медный Прокат купить",
      },
      {
        title: "Латунь",
        link: "tsvetnoi-prokat/brass",
        img: "brassImg",
        metaData: "Латунный Прокат купить",
      },
      {
        title: "Свинец",
        link: "tsvetnoi-prokat/lead",
        img: "leadImg",
        metaData: "Свинцовый Прокат купить",
      },
    ],
  },
  {
    label: "Трубопроводная арматура",
    href: "trubniy-prokat",
    metaData: "Купить Трубопроводная арматура оптом и в розницу",
    links: [
      {
        title: "Запорная Арматура",
        link: "trubniy-prokat/zapor",
        img: "zaporTrubCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Регулирующие ",
        link: "trubniy-prokat/regul",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Обратные",
        link: "trubniy-prokat/obrat",
        img: "clapanRegulCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Защиты",
        link: "trubniy-prokat/zashit",
        img: "clapanZashitCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Предохранительные",
        link: "trubniy-prokat/predohran",
        img: "clapanPredohranCatalog",
        metaData: "Прокат",
      },
      {
        title: "Клапаны Продувки",
        link: "trubniy-prokat/produv",
        img: "clapanProduvCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Черные металлы",
    href: "cherniy-prokat",
    metaData: "Купить Чёрный металлопрокат оптом и в розницу",
    links: [
      {
        title: "Арматура / Катанка",
        link: "cherniy-prokat/armatura",
        img: "armaturaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Балка",
        link: "cherniy-prokat/beam",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса г/к",
        link: "cherniy-prokat/polosa",
        img: "beamCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "cherniy-prokat/corner",
        img: "cornerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "cherniy-prokat/circle",
        img: "circleCatalog",
        metaData: "Прокат",
      },
      {
        title: "Швеллер",
        link: "cherniy-prokat/shveller",
        img: "shvellerCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "cherniy-prokat/pipe",
        img: "pipeCatalog",
        metaData: "Прокат",
      },
      {
        title: "Цинк",
        link: "cherniy-prokat/zinc",
        img: "zincImg",
        metaData: "Цинковый Прокат купить",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Лист",
        link: "cherniy-prokat/list",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Судовая сталь",
        link: "cherniy-prokat/sudovaya_stal",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
      {
        title: "Поковки",
        link: "cherniy-prokat/pokovky",
        img: "provolokaSteel",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Прецензионные сплавы",
    href: "precensplav-prokat",
    metaData: "Купить Прецензионные сплавы оптом и в розницу",
    links: [
      {
        title: "Нихром",
        link: "precensplav/nihrom",
        img: "nihromPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Фехраль",
        link: "precensplav/fehral",
        img: "fehralPrecenCatalog",
        metaData: "Прокат",
      },
      {
        title: "Пермаллой",
        link: "precensplav/permalloy",
        img: "permalloyPrecenCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Нержавеющие металлы",
    href: "nershav-prokat",
    metaData: "Купить Нержавеющий металлопрокат оптом и в розницу",
    links: [
      {
        title: "Лист",
        link: "nershav-prokat/list-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "nershav-prokat/lenta-nershav",
        img: "lentaNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Труба",
        link: "nershav-prokat/truba-nershav",
        img: "pipeNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Уголок",
        link: "nershav-prokat/corner-nershav",
        img: "cornerNershavCatalog",
        metaData: "Прокат",
      },
      // {
      //   title: "Квадрат",
      //   link: "nershav-prokat/square-nershav",
      //   img: "squareNershavCatalog",
      //   metaData: "Прокат",
      // },
      {
        title: "Шестигранник",
        link: "nershav-prokat/hexagon-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Круг",
        link: "nershav-prokat/circle-nershav",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Полоса",
        link: "nershav-prokat/polosa-nershav",
        img: "lineNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Сетка",
        link: "nershav-prokat/grid-nershav",
        img: "gridNershavCatalog",
        metaData: "Прокат",
      },
    ],
  },
  {
    label: "Метизы",
    href: "metizi-prokat",
    metaData: "Купить Метизы оптом и в розницу",
    links: [
      {
        title: "Калибровка",
        link: "metizi-prokat/kalibrovka",
        img: "kalibrovkaCatalog",
        metaData: "Прокат",
      },
      {
        title: "Лента",
        link: "cherniy-prokat/lenta-steel",
        img: "lentaZincCatalog",
        metaData: "Прокат",
      },
      {
        title: "Проволока",
        link: "metizi-prokat/wire-metizi",
        img: "circleNershavCatalog",
        metaData: "Прокат",
      },
      {
        title: "Шпильки",
        link: "metizi-prokat/shpilki",
        img: "shpilkiCatalog",
        metaData: "Прокат",
      },
      {
        title: "Болты и гайки",
        link: "metizi-prokat/bolty-i-gaiky",
        img: "boltyIGayky",
        metaData: "Прокат",
      },
      // {
      //   title: "Сетка",
      //   link: "metizi-prokat/titan",
      //   img: "circleNershavCatalog",
      //   metaData: "Прокат",
      // },
    ],
  },
];
